---

- name: Install pgbackrest
  yum:
    name: pgbackrest
    state: present
  tags: ["install"]

- name: Copy pgbackrest config
  template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest.conf
    owner: "{{ pgbackrest_owner }}"
    group: "{{ pgbackrest_owner }}"
    mode: 0600
  notify: reconfigure pgbackrest

- name: Remove old services
  file:
    path: "/etc/systemd/system/pgbackrest-{{ name }}-{{ backup_type }}.service"
    state: absent
  vars:
    name: "{{ item.0.name }}"
    backup_type: "{{ item.1.backup_type }}"
  loop: "{{ pgbackrest_stanzas | subelements('schedules', skip_missing=True) }}"
  loop_control:
    label: "{{ name }} [{{ backup_type }}]"
  notify: reload systemd

- name: Remove old timers
  file:
    path: "/etc/systemd/system/pgbackrest-{{ name }}-{{ backup_type }}.timer"
    state: absent
  vars:
    name: "{{ item.0.name }}"
    backup_type: "{{ item.1.backup_type }}"
  loop: "{{ pgbackrest_stanzas | subelements('schedules', skip_missing=True) }}"
  loop_control:
    label: "{{ name }} [{{ backup_type }}]"
  notify: reload systemd

- name: Configure services and timers
  include_tasks: config-services.yml
  loop: "{{ range(1, pgbackrest_repos | length + 1) | list }}"
  loop_control:
    loop_var: repo
