---

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "ol${MOLECULE_OL_VERSION:-8}"
    image: "oraclelinux:${MOLECULE_OL_VERSION:-8}"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        postgresql_version: ${MOLECULE_PG_VERSION:-"13"}
        pgbackrest_stanzas:
          - stanza: main
            pg_path: "/var/lib/pgsql/{{ postgresql_version }}/data"
            schedules:
              - backup_type: full
                oncalendar: 'Weekly'
              - backup_type: diff
                oncalendar: 'Hourly'
          - stanza: test
            pg_path: "/var/lib/pgsql/{{ postgresql_version }}/data"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
